"""The intent store: deviations with vanilla-identity addresses, rules, entries and
their states, the proposer and the seeds."""
import json

import pytest

from conftest import build_tracker, _write_tree
from pdxaudit import diff3, intent, proposer
from pdxaudit.base import VanillaBase
from pdxaudit.ledger import empty_state
from pdxaudit.registry import Registry, glob_regex
from pdxaudit.tracker import get_commits

LAW = "in_game/common/laws/l.txt"
LAW_OLD = ("law_a = {\n\tmodifier = {\n\t\tlocal_monthly_food_modifier = 0.1\n\t\tcost = 1\n\t}\n"
           "\tif = { limit = { has_x = yes } add = 1 }\n"
           "\tif = { limit = { has_y = yes } add = 2 }\n"
           "\tif = { limit = { has_y = yes } add = 3 }\n"
           "\tNOT = { has_z = yes }\n}\n"
           "law_b = {\n\tcost = 5\n\tupkeep = 1\n}\n")
LAW_NEW = LAW_OLD.replace("cost = 1\n", "cost = 2\n")
GUI = "in_game/gui/map_markers.gui"
GUI_OLD = 'types M {\n\ttype marker = widget {\n\t\tmax_update_rate = 4\n\t\tsize = { 1 1 }\n\t}\n}\n'

REGISTRY = """
[system.provisions]
files = ["in_game/**/fe_laws*"]
[system.faster_universalis]
files = ["in_game/gui/**"]
[system.economy]
files = ["in_game/common/laws/m.txt"]
[tool.generate_vanilla_overrides]
path = "tools/generate_vanilla_overrides.py"
status = "active"
"""

MOD_LAWS = ("REPLACE:law_a = {\n\tmodifier = {\n\t\tlocal_monthly_food_modifier = 0\n"
            "\t\tlocal_goods_output_modifier = 0.1\n\t\tcost = 1\n\t}\n"
            "\tif = { limit = { has_x = yes } add = 1 }\n"
            "\tif = { limit = { has_y = yes } add = 2 }\n"
            "\tif = { limit = { has_y = yes } add = 30 }\n"
            "\tnot = { has_z = yes }\n}\n")


def _world(tmp_path, mod_laws=MOD_LAWS, extra=None):
    tr = build_tracker(tmp_path, [
        ("1.0", {LAW: LAW_OLD, GUI: GUI_OLD}),
        ("1.1", {LAW: LAW_NEW, GUI: GUI_OLD}),
    ])
    mod = tmp_path / "mod"
    files = {".metadata/metadata.json": '{"id": "t"}', "pdx-maint.toml": REGISTRY,
             "in_game/common/laws/fe_laws.txt": mod_laws,
             GUI: GUI_OLD.replace("max_update_rate = 4", "max_update_rate = 9999 # [FU]"),
             "in_game/common/laws/m.txt": "INJECT:law_b = {\n\tupkeep = 2\n\tnew_key = yes\n}\n",
             "in_game/common/laws/fe_generated_l.txt":
                 "# AUTO-GENERATED by generate_vanilla_overrides.py from l.txt. Do not hand-edit.\n"}
    files.update(extra or {})
    _write_tree(mod, files)
    commits = get_commits(tr.repo)
    copies, devs = intent.run_collect(mod, VanillaBase(tr.repo), commits, *commits[0])
    return mod, copies, devs


def _dev(devs, **kw):
    hit = [d for d in devs if all(getattr(d, k) == v for k, v in kw.items())]
    assert len(hit) == 1, (kw, [(d.identity, d.path, d.change) for d in devs])
    return hit[0]


def test_deviations_carry_vanilla_identity_and_addresses(tmp_path):
    _mod, _copies, devs = _world(tmp_path)
    food = _dev(devs, mod_key="local_monthly_food_modifier")
    assert food.identity == "in_game/common/laws/law_a" and food.copy == "replace"
    assert [s["key"] for s in food.path] == ["modifier", "local_monthly_food_modifier"]
    assert food.systems == ["provisions"]
    added = _dev(devs, mod_key="local_goods_output_modifier")
    assert added.change == "mod_added" and added.vanilla_text is None


def test_keyword_case_is_no_deviation(tmp_path):
    _mod, _copies, devs = _world(tmp_path)
    assert not [d for d in devs if "NOT" in d.keys or "not" in d.keys]
    assert diff3.nodes("NOT = { a = 1 }")[0].sig == diff3.nodes("not = { a = 1 }")[0].sig


def test_a_repeated_if_is_addressed_by_selector_and_position(tmp_path):
    _mod, _copies, devs = _world(tmp_path)
    d = _dev(devs, mod_value="30")
    seg = d.path[0]
    assert seg["key"] == "if" and seg["sel"].startswith("limit#") and seg["n"] == 2
    assert d.path[1] == {"key": "add"}


def test_identity_survives_a_move_to_another_mod_file(tmp_path):
    _m, _c, devs = _world(tmp_path / "a")
    a = {(d.identity, json.dumps(d.path), d.change) for d in devs if d.copy == "replace"}
    # the same REPLACE in another file name of the same folder
    mod_b = tmp_path / "c"
    _m, _c, other = _world(mod_b, extra={"in_game/common/laws/fe_laws.txt": "",
                                          "in_game/common/laws/zz_moved.txt": MOD_LAWS})
    b = {(d.identity, json.dumps(d.path), d.change) for d in other if d.copy == "replace"}
    assert a == b and a


def test_inject_children_are_deviations(tmp_path):
    _mod, _copies, devs = _world(tmp_path)
    inj = sorted((d.mod_key, d.change) for d in devs if d.copy == "inject")
    assert inj == [("new_key", "mod_added"), ("upkeep", "mod_changed")]


def test_comment_and_generated_files(tmp_path):
    _mod, _copies, devs = _world(tmp_path)
    fu = _dev(devs, mod_key="max_update_rate")
    assert fu.comment == "[FU]" and fu.copy == "gui_file"
    rule = {"id": "fu", "match": {"comment": ["[FU]"]}}
    assert intent.rule_matches(rule, fu)
    reg = Registry(_mod)
    assert reg.generated_by("in_game/common/laws/fe_generated_l.txt") == (True, "generate_vanilla_overrides")
    assert reg.generated_by("in_game/common/laws/fe_laws.txt") == (False, None)


def test_matcher_fields(tmp_path):
    _mod, _copies, devs = _world(tmp_path)
    food = _dev(devs, mod_key="local_monthly_food_modifier")
    m = lambda **match: intent.rule_matches({"id": "r", "match": match}, food)   # noqa: E731
    assert m(vanilla_key=["re:^(local_|global_)?monthly_food_modifier$"])
    assert m(content=["in_game/common/laws"], audit=["replace"], block=["law_*"])
    assert m(path=["modifier.*"]) and m(path=["**"]) and not m(path=["*"])
    assert m(file=["in_game/common/laws/fe_*.txt"])
    assert m(change=["mod_changed"]) and not m(change=["mod_added"])
    assert m(vanilla_absent=False) and not m(vanilla_absent=True)
    assert m(name=["local_monthly_food_modifier"]) and not m(name=["monthly_food"])


def _rule(**kw):
    rule = {"id": "provisions.food_cancels", "system": "provisions", "reason": "Provisions are the only food.",
            "source": {"kind": "note", "ref": "176"}, "disposition": "keep_mod",
            "match": {"vanilla_key": ["re:^(local_|global_)?monthly_food_modifier$"]}}
    rule.update(kw)
    return rule


def test_store_validation(tmp_path):
    mod, _c, _d = _world(tmp_path)
    reg = Registry(mod)
    state = empty_state()
    intent.add_rule(state, _rule(), reg)
    with pytest.raises(intent.IntentError, match="not a system"):
        intent.add_rule(state, _rule(system="nope"), reg)
    with pytest.raises(intent.IntentError, match="reason"):
        intent.add_rule(state, _rule(reason=" "), reg)
    with pytest.raises(intent.IntentError, match="disposition"):
        intent.add_rule(state, _rule(disposition="maybe"), reg)
    with pytest.raises(intent.IntentError, match="unknown match"):
        intent.add_rule(state, _rule(match={"colour": ["x"]}), reg)
    with pytest.raises(intent.IntentError, match="not a tool"):
        intent.add_rule(state, _rule(tool="nope"), reg)
    intent.add_rule(state, _rule(id="fu", system="faster_universalis", disposition=None,
                                 match={"comment": ["[FU]"]}), reg)      # a grouping
    assert set(intent.of(state)["rules"]) == {"provisions.food_cancels", "fu"}


def test_attribution_entry_over_rule_and_rule_conflicts(tmp_path):
    _mod, copies, devs = _world(tmp_path)
    state = empty_state()
    intent.add_rule(state, _rule())
    food = _dev(devs, mod_key="local_monthly_food_modifier")
    it = intent.of(state)
    assert intent.attribute(food, it).by == "rule:provisions.food_cancels"
    entry = intent.entry_from(food, "e1", "economy", "keep the modifier block", {"kind": "user"},
                              "take_vanilla", depth=1)
    intent.seal(entry, copies, devs)
    intent.add_entry(state, entry)
    a = intent.attribute(food, it, intent.entry_states(it, copies, devs))
    assert (a.by, a.disposition) == ("entry:e1", "take_vanilla")
    added = _dev(devs, mod_key="local_goods_output_modifier")
    assert intent.attribute(added, it).by == "entry:e1"          # the subtree covers it
    intent.remove(state, "e1")
    intent.add_rule(state, _rule(id="other", disposition="take_vanilla"))
    a = intent.attribute(food, it)
    assert a.by is None and a.conflict == ["other", "provisions.food_cancels"]


def test_entry_states(tmp_path):
    _mod, copies, devs = _world(tmp_path)
    d = _dev(devs, mod_value="30")
    state = empty_state()
    entry = intent.entry_from(d, "e1", "economy", "SUL value", {"kind": "user"}, "keep_mod")
    intent.seal(entry, copies, devs)
    intent.add_entry(state, entry)
    it = intent.of(state)
    assert intent.entry_states(it, copies, devs)["e1"] == ("recorded", "")
    # the mod changes the node: stale on the mod side
    _m, copies2, devs2 = _world(tmp_path / "x", mod_laws=MOD_LAWS.replace("add = 30", "add = 31"))
    assert intent.entry_states(it, copies2, devs2)["e1"] == ("stale", "mod changed")
    # the mod drops the REPLACE: the copy is gone
    _m, copies3, devs3 = _world(tmp_path / "y", mod_laws="")
    assert intent.entry_states(it, copies3, devs3)["e1"][0] == "lost"


def test_proposer_groups_and_never_fills_a_reason_from_comments(tmp_path):
    mod, copies, devs = _world(tmp_path)
    notes = [{"id": "176", "title": "t", "body": "- law_a keeps its food modifier: provisions.\n"}]
    cands = proposer.propose(mod, copies, devs, empty_state(), notes, "2026-10-02")
    fu = next(c for c in cands if any(m["identity"].startswith("guifile:") for m in c["members"]))
    assert fu["record"]["reason"] == "" and fu["record"]["source"] == {"kind": "user"}
    assert "[FU]" in fu["evidence"]["comments"]
    law = [c for c in cands if any(m["identity"].endswith("/law_a") for m in c["members"])]
    assert law and all(c["record"]["reason"] == "law_a keeps its food modifier: provisions." for c in law)
    assert all(c["record"]["source"] == {"kind": "note", "ref": "176"} for c in law)
    assert all(c["record"]["disposition"] == "" for c in cands)
    assert not any(m["identity"].startswith("in_game/common/laws/fe_generated") for c in cands
                   for m in c["members"])


def test_accept_needs_a_disposition_and_a_reason(tmp_path):
    mod, copies, devs = _world(tmp_path)
    cands = proposer.propose(mod, copies, devs, empty_state(), [], "2026-10-02")
    path = proposer.write(cands, tmp_path, "t", "1.1", tmp_path / "p.json")
    state = empty_state()
    added, errors = proposer.accept(state, path, ["c1"], Registry(mod))
    assert not added and "choose a disposition" in errors[0]
    doc = json.loads(path.read_text())
    doc["candidates"][0]["record"]["disposition"] = "keep_mod"
    path.write_text(json.dumps(doc))
    added, errors = proposer.accept(state, path, ["c1"], Registry(mod))
    assert not added and "reason" in errors[0]
    doc["candidates"][0]["record"]["reason"] = "SUL design"
    doc["candidates"][0]["record"]["system"] = "economy"
    path.write_text(json.dumps(doc))
    added, errors = proposer.accept(state, path, ["c1", "c99"], Registry(mod))
    assert added and errors == ["c99: no such candidate"]


def test_seeds_from_dismissals_and_the_keep_file(tmp_path):
    mod, copies, devs = _world(tmp_path)
    cost = _dev(devs, mod_key="cost", copy="replace")
    assert cost.change == "vanilla_changed" and cost.finding
    state = empty_state()
    state["dismissed"][cost.finding] = {"finding": "x", "reason": "SUL keeps the old cost"}
    state["dismissed"]["f" * 40] = {"finding": "x"}                  # no reason: no seed
    cands = proposer.seed_dismissals(copies, devs, state, "2026-10-02")
    assert len(cands) == 1 and cands[0]["record"]["reason"] == "SUL keeps the old cost"
    assert cands[0]["record"]["address"]["path"] == cost.path
    keep = tmp_path / "keep.txt"
    keep.write_text("# comment\nlaw_a.modifier   provisions: goods output in place of food\nlaw_z.x  gone\n")
    found, unmatched = proposer.seed_keep_file(copies, devs, keep, "2026-10-02")
    assert unmatched == ["law_z.x"]
    rec = found[0]["record"]
    assert rec["address"]["path"] == [{"key": "modifier"}] and rec["scope"] == "subtree"
    assert rec["seen"]["mod_sig"] and rec["disposition"] == "keep_mod"


def test_seed_rules_takes_the_reason_from_the_named_note(tmp_path):
    mod, copies, devs = _world(tmp_path)
    rules = tmp_path / "rules.json"
    rules.write_text(json.dumps([dict(_rule(reason=""), reason_from="food cancels")]))
    notes = [{"id": "176", "title": "", "body": "- Goods output modifiers: food cancels, see laws.\n"}]
    cands = proposer.seed_rules(devs, rules, notes)
    assert cands[0]["record"]["reason"] == "Goods output modifiers: food cancels, see laws."
    assert cands[0]["selects"] == 1 and "reason_from" not in cands[0]["record"]


def test_registry_globs():
    assert glob_regex("in_game/**/fe_projection*").match("in_game/common/x/fe_projection_a.txt")
    assert glob_regex("in_game/**/fe_projection*").match("in_game/fe_projection.txt")
    assert not glob_regex("in_game/*/x.txt").match("in_game/a/b/x.txt")


def test_cli_add_rule_list_propose_accept(tmp_path, monkeypatch, capsys):
    from pdxaudit.intent_cli import main
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    mod, _c, _d = _world(tmp_path)
    repo = str(tmp_path / "vanilla-tracker" / "repo.git")
    common = ["--mod-root", str(mod), "--vanilla-repo", repo]
    rule = tmp_path / "rule.json"
    rule.write_text(json.dumps(_rule()))
    assert main(common + ["add-rule", str(rule)]) == 0
    assert main(common + ["--json", "list"]) == 0
    out = capsys.readouterr().out
    rows = json.loads(out[out.index("["):])
    assert rows[0]["id"] == "provisions.food_cancels" and rows[0]["covers"] == 1
    prop = tmp_path / "prop.json"
    assert main(common + ["propose", "--out", str(prop)]) == 0
    doc = json.loads(prop.read_text())
    assert doc["kind"] == proposer.PROPOSAL_KIND and doc["vanilla"] == "1.1"
    assert not any(m["mod"] and "local_monthly_food_modifier" in m["mod"]
                   for c in doc["candidates"] for m in c["members"])     # the rule explains it
    assert main(common + ["accept", str(prop), "--only", "c1"]) == 1   # no disposition chosen yet
    assert main(common + ["remove", "provisions.food_cancels"]) == 0


def test_every_override_prefix_is_a_copy(tmp_path):
    """TRY_REPLACE and REPLACE_OR_CREATE are REPLACE copies; TRY_INJECT and
    INJECT_OR_CREATE are INJECT copies."""
    extra = {"in_game/common/laws/fe_laws.txt": MOD_LAWS.replace("REPLACE:", "TRY_REPLACE:"),
             "in_game/common/laws/m.txt": "TRY_INJECT:law_b = {\n\tnew_key = yes\n}\n",
             "in_game/common/laws/n.txt": "REPLACE_OR_CREATE:law_c = {\n\tx = 1\n}\n"}
    _mod, _copies, devs = _world(tmp_path, extra=extra)
    assert _dev(devs, mod_key="local_monthly_food_modifier").copy == "replace"
    assert _dev(devs, mod_key="new_key").copy == "inject"
