"""pdx-audit merge: the dry run writes a plan and nothing in the mod; --apply writes
only what the plan holds, and refuses a file that changed, failed the removed-line
check, holds an open decision or uses a stale entry."""
import json

from conftest import build_tracker, _write_tree
from pdxaudit.merge_cli import main

LAW = "in_game/common/laws/l.txt"
V1 = "law_a = {\n\tcost = 1\n\tx = 1\n}\n"
V2 = "law_a = {\n\tcost = 2\n\tx = 1\n\tnew = 1\n}\n"
MOD = "﻿REPLACE:law_a = {\n\tcost = 1\n\tx = 5\n}\n"
FE = "in_game/common/laws/fe.txt"


def _setup(tmp_path, monkeypatch, mod_text=MOD, extra=None):
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    tr = build_tracker(tmp_path, [("1.0", {LAW: V1}), ("1.1", {LAW: V2})])
    mod = tmp_path / "mod"
    files = {".metadata/metadata.json": '{"id": "t"}', FE: mod_text}
    files.update(extra or {})
    _write_tree(mod, files)
    common = ["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1"]
    return mod, common


def test_dry_run_writes_nothing_and_apply_writes_the_plan(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch)
    before = (mod / FE).read_bytes()
    plan = tmp_path / "plan.json"
    assert main(common + ["--dry-run", "--plan-out", str(plan)]) == 0
    out = capsys.readouterr().out
    assert (mod / FE).read_bytes() == before
    assert "+\tcost = 2" in out and "+\tnew = 1" in out and "Removed-line check: passed" in out
    assert main(common + ["--apply", str(plan)]) == 0
    after = (mod / FE).read_bytes()
    assert after.startswith(b"\xef\xbb\xbf")                       # the BOM stays
    assert after.decode("utf-8-sig") == "REPLACE:law_a = {\n\tcost = 2\n\tx = 5\n\tnew = 1\n}\n"


def test_apply_refuses_a_file_that_changed_after_the_dry_run(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch)
    plan = tmp_path / "plan.json"
    main(common + ["--dry-run", "--plan-out", str(plan)])
    (mod / FE).write_text(MOD.replace("x = 5", "x = 6"), encoding="utf-8")
    assert main(common + ["--apply", str(plan)]) == 1
    assert "changed after the dry run" in capsys.readouterr().err
    assert "cost = 1" in (mod / FE).read_text(encoding="utf-8-sig")


def test_apply_refuses_open_decisions_and_failed_checks(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch, MOD.replace("cost = 1", "cost = 3"))
    plan = tmp_path / "plan.json"
    main(common + ["--dry-run", "--plan-out", str(plan)])
    p = json.loads(plan.read_text())
    assert p["files"][0]["open"] == 1
    [d] = [d for d in p["files"][0]["decisions"] if d["action"] == "open"]
    # The plan holds the three texts of the decision, and the base version apart.
    assert (d["base"], d["ours"], d["theirs"], d["base_version"]) == ("cost = 1", "cost = 3", "cost = 2", "1.0")
    assert main(common + ["--apply", str(plan)]) == 1
    assert "open decisions" in capsys.readouterr().err
    p["files"][0]["open"] = 0
    p["files"][0]["removed_check"] = {"passed": False, "unexplained": [{"line": 2, "text": "x"}]}
    plan.write_text(json.dumps(p))
    assert main(common + ["--apply", str(plan)]) == 1
    assert "removed-line check failed" in capsys.readouterr().err


def test_generated_files_are_listed_to_regenerate(tmp_path, monkeypatch, capsys):
    reg = '[tool.gen]\npath = "tools/gen.py"\nstatus = "active"\n'
    mod, common = _setup(tmp_path, monkeypatch, "# AUTO-GENERATED by gen.py\n" + MOD.lstrip("﻿"),
                         {"pdx-maint.toml": reg})
    assert main(common + ["--dry-run", "--plan-out", str(tmp_path / "p.json")]) == 0
    out = capsys.readouterr().out
    assert "not merged; regenerate with `pdx-maint run gen`" in out
    assert "```diff" not in out


def test_a_repeated_key_merges_and_keeps_the_definitions_between(tmp_path, monkeypatch, capsys):
    """Vanilla 1.3.11 messagetypes.txt holds INDEPENDANCE two times, and 1.4 removes
    the second. The file audit reads both blocks as one copy, with the definitions
    between them blank. The merge must find that copy and keep those definitions."""
    path = "main_menu/gui/messagetypes.txt"
    v1 = "A={\nlog=yes\n}\n\nB={\nlog=yes\n}\n\nA={\nlog=no\n}\n\nC={\nlog=yes\n}\n"
    v2 = "A={\nlog=yes\n}\n\nB={\nlog=yes\n}\n\nC={\nlog=yes\n}\n"
    mod_text = ("﻿A = {\n\tlog = yes\n}\n\nB = {\n\tlog = yes\n\tmine = 1\n}\n\n"
                "A = {\n\tlog = no\n}\n\nC = {\n\tlog = yes\n}\n")
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    tr = build_tracker(tmp_path, [("1.0", {path: v1}), ("1.1", {path: v2})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', path: mod_text})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    p = json.loads(plan.read_text(encoding="utf-8"))
    assert not p["skipped"]
    [f] = p["files"]
    assert f["removed_check"]["passed"] and not f["open"]
    assert f["merged"] == "A = {\n\tlog = yes\n}\n\nB = {\n\tlog = yes\n\tmine = 1\n}\n\nC = {\n\tlog = yes\n}\n"


DEFS = "in_game/common/x/defs.txt"
GEN = "in_game/common/x/gen.txt"


def _block(name, v=1):
    return f"{name} = {{\n\tv = {v}\n}}\n"


def test_new_vanilla_definitions_go_to_vanilla_positions(tmp_path, monkeypatch):
    """Vanilla adds A (start), C (middle) and G (end). The mod deleted E and F: E
    stays deleted and is an open decision, because vanilla changed it. F stays
    deleted with no decision. The mod's own M keeps its place. A generated file
    gets no new definition: it goes to the regenerate list."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    v1 = "\n".join(_block(n) for n in "BDEF")
    v2 = "\n".join([_block("A"), _block("B"), _block("C"), _block("D", 2), _block("E", 2), _block("F"),
                    _block("G")])
    tr = build_tracker(tmp_path, [("1.0", {DEFS: v1, GEN: _block("P")}),
                                  ("1.1", {DEFS: v2, GEN: _block("P") + "\n" + _block("Q")})])
    mod = tmp_path / "mod"
    reg = '[tool.gen]\npath = "tools/gen.py"\nstatus = "active"\n'
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', "pdx-maint.toml": reg,
                      DEFS: "\n".join(_block(n) for n in "BDM"),
                      GEN: "# AUTO-GENERATED by gen.py\n" + _block("P")})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    p = json.loads(plan.read_text(encoding="utf-8"))
    [f] = p["files"]
    assert f["file"] == DEFS and f["removed_check"]["passed"]
    assert f["merged"] == "\n".join([_block("A"), _block("B"), _block("C"), _block("D", 2), _block("G"),
                                     _block("M")])
    assert "+G = {" in f["diff"]
    added = [d["path"][0]["key"] for d in f["decisions"] if d["kind"] == "vanilla_added"]
    assert added == ["A", "C", "G"]
    assert [(d["kind"], d["path"][0]["key"]) for d in f["decisions"] if d["action"] == "open"] == \
        [("removed_changed", "E")]
    assert [r["file"] for r in p["regenerate"]] == [GEN]


def _rules(tmp_path, mod, rules):
    from pdxaudit.intent_cli import main as intent_main
    f = tmp_path / "rules.json"
    f.write_text(json.dumps(rules), encoding="utf-8")
    assert intent_main(["--mod-root", str(mod), "add-rule", str(f)]) == 0


CLIM = "in_game/common/climates/00_default.txt"
UNITS = "in_game/common/unit_types/0_knights.txt"
GOODS = "in_game/common/goods/00_raw.txt"
MSG = "main_menu/gui/messagetypes.txt"


def test_new_definitions_pass_through_the_intent_store(tmp_path, monkeypatch):
    """Vanilla adds one definition to each of four same-path files, and changes one
    that the mod deleted. A keep_mod rule keeps the new climate out; a rule without a
    disposition makes the new unit an open decision; the goods file belongs to a
    pdx-maint system, so with no rule its new good is open; the message file has no
    owner, so its new message goes in. A take_vanilla rule puts back the deleted
    unit that vanilla changed."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    v1 = {CLIM: _block("temperate"), UNITS: _block("knight") + "\n" + _block("old_knight"),
          GOODS: _block("wheat"), MSG: _block("A")}
    v2 = {CLIM: _block("temperate") + "\n" + _block("subpolar"),
          UNITS: _block("knight") + "\n" + _block("old_knight", 2) + "\n" + _block("order_knight"),
          GOODS: _block("wheat") + "\n" + _block("camels"), MSG: _block("A") + "\n" + _block("B")}
    tr = build_tracker(tmp_path, [("1.0", v1), ("1.1", v2)])
    mod = tmp_path / "mod"
    reg = ('[system.climate]\nfiles = []\n[system.combat]\nfiles = []\n'
           '[system.economy]\nfiles = ["in_game/common/goods/*.txt"]\n')
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', "pdx-maint.toml": reg,
                      CLIM: _block("temperate", 5), UNITS: _block("knight", 5), GOODS: _block("wheat", 5),
                      MSG: _block("A", 5)})
    common = {"source": {"kind": "user"}}
    _rules(tmp_path, mod, [
        dict(common, id="climate.no_vanilla_climates", system="climate", disposition="keep_mod",
             reason="SUL uses only its own climate classes.",
             match={"content": ["in_game/common/climates"], "change": ["vanilla_added"]}),
        dict(common, id="combat.new_units", system="combat", disposition=None,
             reason="SUL's unit files use rescaled stats.",
             match={"content": ["in_game/common/unit_types"], "change": ["vanilla_added"], "path": [""]}),
        dict(common, id="combat.restore_old_knight", system="combat", disposition="take_vanilla",
             reason="Test: take vanilla's old_knight back.",
             match={"block": ["old_knight"], "change": ["removed_changed"]})])
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    p = json.loads(plan.read_text(encoding="utf-8"))
    files = {f["file"]: f for f in p["files"]}
    got = {(f, d["path"][0]["key"]): (d["kind"], d["action"], d.get("by")) for f, x in files.items()
           for d in x["decisions"] if d["path"] and d["path"][0]["key"] in
           ("subpolar", "order_knight", "old_knight", "camels", "B")}
    assert got == {
        (CLIM, "subpolar"): ("vanilla_added", "keep", "rule:climate.no_vanilla_climates"),
        (UNITS, "order_knight"): ("vanilla_added", "open", "rule:combat.new_units"),
        (UNITS, "old_knight"): ("removed_changed", "take", "rule:combat.restore_old_knight"),
        (GOODS, "camels"): ("vanilla_added", "open", None),
        (MSG, "B"): ("vanilla_added", "take", None)}
    assert "subpolar" not in files[CLIM]["merged"]
    assert "camels" not in files[GOODS]["merged"]
    assert "system economy owns the file" in next(d["reason"] for d in files[GOODS]["decisions"]
                                                    if d["path"][0]["key"] == "camels")
    assert "order_knight" not in files[UNITS]["merged"]
    assert files[UNITS]["merged"] == _block("knight", 5) + "\n" + _block("old_knight", 2)
    assert files[MSG]["merged"] == _block("A", 5) + "\n" + _block("B")


def test_a_file_vanilla_added_after_old_merges_with_an_empty_base(tmp_path, monkeypatch):
    """The mod holds its own file at a path where vanilla adds a file after --old.
    Vanilla held .txt files at --old, so it did not hold this one: the base is empty.
    A definition alike on both sides stays once, vanilla's new definition goes in, and
    a definition both sides hold in different forms is an open both_added decision."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    late = "in_game/common/x/late.txt"
    tr = build_tracker(tmp_path, [("1.0", {DEFS: _block("Z")}),
                                  ("1.1", {DEFS: _block("Z"), late: "\n".join(_block(n) for n in "ABC")})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}',
                      late: _block("A") + "\n" + _block("B", 7) + "\n" + _block("M")})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    p = json.loads(plan.read_text(encoding="utf-8"))
    assert not p["skipped"]
    [f] = p["files"]
    assert f["merged"] == "\n".join([_block("A"), _block("B", 7), _block("C"), _block("M")])
    got = sorted((d["kind"], d["action"], d["copy"], d["base_version"]) for d in f["decisions"])
    assert got == [("both_added", "open", "B", "(none)"), ("vanilla_added", "take", "C", "1.0")]
    assert f["removed_check"]["passed"]


def test_a_file_type_the_tracker_did_not_record_at_old_is_skipped_with_the_reason(tmp_path, monkeypatch):
    """The tracker recorded .map files only from 1.1. Vanilla held default.map at 1.0,
    but no version of it is known, so the merge has no base: it lists the file once,
    with the reason, and merges nothing in it."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    dm = "in_game/map_data/default.map"
    tr = build_tracker(tmp_path, [("1.0", {DEFS: _block("Z")}),
                                  ("1.1", {DEFS: _block("Z"), dm: "lakes = { 1 2 }\nseas = { 3 }\n"})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', dm: "lakes = { 1 }\nseas = { 3 4 }\n"})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    p = json.loads(plan.read_text(encoding="utf-8"))
    assert not p["files"]
    assert [(s["file"], s["copies"] >= 1) for s in p["skipped"]] == [(dm, True)]
    assert "the tracker holds no .map files at 1.0" in p["skipped"][0]["why"]


def _plan(tmp_path, mod, tr, *extra):
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan), *extra]) == 0
    return json.loads(plan.read_text(encoding="utf-8"))


def test_the_merged_text_gets_the_layout_of_pdx_format(tmp_path, monkeypatch):
    """Vanilla adds a definition in its own layout (`B={\\nv=1\\n}`). The mod file is
    in pdx-format layout, so the plan formats the merged file with pdx-format: the
    file needs no format pass after --apply. A file that is not in pdx-format layout
    keeps its own layout."""
    import shutil
    import pytest
    from pdxaudit import merge_cli
    if not shutil.which("pdx-format"):
        pytest.skip("pdx-format is not installed")
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    other = "in_game/common/x/other.txt"
    tr = build_tracker(tmp_path, [("1.0", {DEFS: "A={\nv=1\n}\n", other: "C={\nv=1\n}\n"}),
                                  ("1.1", {DEFS: "A={\nv=1\n}\nB={\nv=1 # vanilla note\n}\n",
                                           other: "C={\nv=1\n}\nD={\nv=1\n}\n"})])
    mod = tmp_path / "mod"
    clean = merge_cli.pdx_format({"x.txt": "A = {\n\tv = 1\n\tw = 2\n}\n"})["x.txt"]
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', DEFS: clean,
                      other: "C = {  v = 1 }\n"})
    p = _plan(tmp_path, mod, tr)
    files = {f["file"]: f for f in p["files"]}
    f = files[DEFS]
    assert f["format"] == {"applied": True}
    assert f["merged"] == merge_cli.pdx_format({"m.txt": f["merged"]})["m.txt"]
    assert "B = {" in f["merged"] and "# vanilla note" in f["merged"]
    assert f["removed_check"]["passed"]
    g = files[other]
    assert not g["format"]["applied"] and "not in pdx-format layout" in g["format"]["why"]
    assert "C = {  v = 1 }" in g["merged"] and "D={" in g["merged"]


def test_apply_refuses_a_file_that_pdx_format_refused(tmp_path, monkeypatch, capsys):
    from pdxaudit import merge_cli
    monkeypatch.setattr(merge_cli, "FORMATTER",
                        lambda texts: {k: (v if k.startswith("ours/") else None) for k, v in texts.items()})
    mod, common = _setup(tmp_path, monkeypatch)
    plan = tmp_path / "plan.json"
    main(common + ["--dry-run", "--plan-out", str(plan)])
    p = json.loads(plan.read_text())
    assert p["files"][0]["format"]["failed"]
    assert main(common + ["--apply", str(plan)]) == 1
    assert "pdx-format refused the merged text" in capsys.readouterr().err


def test_an_old_version_that_is_not_tracked_is_an_error(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch)
    common[common.index("--old") + 1] = "0.9"
    assert main(common + ["--dry-run", "--plan-out", str(tmp_path / "p.json")]) == 2
    assert "--old 0.9 is not a tracked version" in capsys.readouterr().err


def test_copies_whose_vanilla_text_is_gone_are_decisions(tmp_path, monkeypatch):
    """Vanilla removes, after --old, the block of a REPLACE, the target of an INJECT,
    and a whole same-path file. Each is a vanilla_removed decision: open with no rule;
    a take_vanilla rule deletes the INJECT block; a whole file stays open, because
    --apply never deletes a file. A REPLACE whose block vanilla removed before --old
    is not a change of this window."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    laws = "in_game/common/laws/l.txt"
    gone_file = "in_game/common/x/gone.txt"
    v0 = {laws: "ancient = {\n\tx = 1\n}\nlaw_a = {\n\tx = 1\n}\nlaw_b = {\n\tx = 1\n}\n", gone_file: _block("G")}
    v1 = {laws: "law_a = {\n\tx = 1\n}\nlaw_b = {\n\tx = 1\n}\n", gone_file: _block("G")}
    v2 = {laws: "law_c = {\n\tx = 1\n}\n", DEFS: _block("Z")}
    tr = build_tracker(tmp_path, [("0.9", v0), ("1.0", v1), ("1.1", v2)])
    mod = tmp_path / "mod"
    fe = "in_game/common/laws/fe.txt"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}',
                      fe: "REPLACE:law_a = {\n\tx = 5\n}\n\nINJECT:law_b = {\n\ty = 1\n}\n\n"
                          "REPLACE:ancient = {\n\tx = 2\n}\n",
                      gone_file: _block("G", 3)})
    _rules(tmp_path, mod, [{"id": "laws.drop_dead_injects", "system": "laws", "disposition": "take_vanilla",
                            "reason": "Test: an INJECT into a removed law goes.", "source": {"kind": "user"},
                            "match": {"audit": ["inject"], "change": ["vanilla_removed"]}}])
    p = _plan(tmp_path, mod, tr)
    files = {f["file"]: f for f in p["files"]}
    got = sorted((f, d["path"][0]["key"], d["kind"], d["action"]) for f, x in files.items()
                 for d in x["decisions"])
    assert got == [(fe, "law_a", "vanilla_removed", "open"), (fe, "law_b", "vanilla_removed", "take"),
                   (gone_file, gone_file, "vanilla_removed", "open")]
    assert files[fe]["merged"] == "REPLACE:law_a = {\n\tx = 5\n}\n\nREPLACE:ancient = {\n\tx = 2\n}\n"
    assert "does not delete a file" in files[gone_file]["decisions"][0]["reason"]


def test_text_the_merge_cannot_compare_node_by_node_is_listed(tmp_path, monkeypatch):
    """A .csv file is not script: vanilla's change to it is listed with the reason,
    never dropped without a word."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    csv = "in_game/map_data/ports.csv"
    tr = build_tracker(tmp_path, [("1.0", {csv: "a;1\nb;2\nc;3\n"}), ("1.1", {csv: "a;1\nb;5\nc;3\n"})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', csv: "a;9\nb;2\nc;3\n"})
    p = _plan(tmp_path, mod, tr)
    assert [(s["file"], "not script" in s["why"]) for s in p["skipped"]] == [(csv, True)]


def test_a_generated_file_is_listed_to_regenerate_and_never_skipped(tmp_path, monkeypatch):
    """A tool's manifest lists default.map. The tracker has no .map file at --old, but
    the file goes to the regenerate list only: the tool reads vanilla again."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    dm = "in_game/map_data/default.map"
    tr = build_tracker(tmp_path, [("1.0", {DEFS: _block("Z")}),
                                  ("1.1", {DEFS: _block("Z"), dm: "lakes = { 1 2 }\n"})])
    mod = tmp_path / "mod"
    reg = '[tool.rivers]\npath = "tools/rivers/"\nstatus = "active"\noutputs = ["manifest:tools/rivers/m.json"]\n'
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', "pdx-maint.toml": reg,
                      "tools/rivers/m.json": json.dumps([dm]), dm: "lakes = { 1 }\n"})
    p = _plan(tmp_path, mod, tr)
    assert not p["skipped"] and [r["file"] for r in p["regenerate"]] == [dm]


def test_a_file_with_no_tracker_history_is_skipped_with_the_reason(tmp_path, monkeypatch):
    """The tracker holds no .splnet file in any version. The mod copies one from the
    installed game, so the file audit reports it as file_untracked. The merge has no
    vanilla version to compare, so it lists the file with the reason."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    net = "in_game/map_data/roads.splnet"
    install = tmp_path / "game"
    _write_tree(install, {net: "vanilla net\n"})
    monkeypatch.setenv("PDX_GAME_ROOT", str(install))
    tr = build_tracker(tmp_path, [("1.0", {DEFS: _block("Z")}), ("1.1", {DEFS: _block("Z", 2)})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', net: "mod net\n"})
    p = _plan(tmp_path, mod, tr)
    assert not p["files"]
    assert [(s["file"], "the tracker holds no version of this file" in s["why"]) for s in p["skipped"]] \
        == [(net, True)]
    assert "differs from the installed game" in p["skipped"][0]["why"]


def test_a_copy_with_a_base_older_than_old_opens_the_older_changes(tmp_path, monkeypatch):
    """The REPLACE matches vanilla 1.0. Vanilla changed cost in 1.1 (before --old)
    and x in 1.2. The plan takes x and leaves cost open, so --apply refuses the file
    until the user decides it."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    law = "in_game/common/laws/l.txt"
    tr = build_tracker(tmp_path, [("1.0", {law: "law_a = {\n\tcost = 1\n\tx = 1\n}\n"}),
                                  ("1.1", {law: "law_a = {\n\tcost = 2\n\tx = 1\n}\n"}),
                                  ("1.2", {law: "law_a = {\n\tcost = 2\n\tx = 3\n}\n"})])
    mod = tmp_path / "mod"
    fe = "in_game/common/laws/fe.txt"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}',
                      fe: "REPLACE:law_a = {\n\tcost = 1\n\tx = 1\n\tmine = yes\n}\n"})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.1", "--new", "1.2",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    [f] = json.loads(plan.read_text(encoding="utf-8"))["files"]
    got = {d["path"][0]["key"]: d for d in f["decisions"]}
    assert (got["x"]["action"], got["cost"]["action"]) == ("take", "open")
    assert got["cost"]["base_version"] == "1.0" and "before --old 1.1" in got["cost"]["reason"]
    assert f["open"] == 1


def test_a_rule_on_a_node_of_a_file_definition_decides_it_in_the_merge(tmp_path, monkeypatch):
    """The intent store addresses a node of a same-path file definition from inside
    the definition (path ["x"]), as intent check reports it. The merge uses the same
    address, so a keep_mod rule on ["x"] keeps the mod's x, and vanilla's y is taken."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    tr = build_tracker(tmp_path, [("1.0", {DEFS: "A = {\n\tx = 1\n\ty = 1\n}\n"}),
                                  ("1.1", {DEFS: "A = {\n\tx = 2\n\ty = 3\n}\n"})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', DEFS: "A = {\n\tx = 5\n\ty = 1\n}\n"})
    _rules(tmp_path, mod, [{"id": "x.keep", "system": "x", "disposition": "keep_mod",
                            "reason": "Test: the mod's x stays.", "source": {"kind": "user"},
                            "match": {"content": ["in_game/common/x"], "path": ["x"]}}])
    p = _plan(tmp_path, mod, tr)
    [f] = p["files"]
    got = {d["path"][-1]["key"]: (d["action"], [s["key"] for s in d["path"]]) for d in f["decisions"]}
    assert got == {"x": ("keep", ["x"]), "y": ("take", ["y"])}
    assert f["merged"] == "A = {\n\tx = 5\n\ty = 3\n}\n"


def test_a_line_vanilla_removed_before_the_base_is_not_the_mods_own(tmp_path, monkeypatch):
    """The copy matches 1.1 best (a = 2), but it still holds `flag = no`, which
    vanilla removed in 1.1. That line is vanilla's old text, not the mod's own: the
    merge makes it a vanilla_removed decision, open because the change is older
    than --old. Vanilla's change to b in 1.3 is taken."""
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    law = "in_game/common/laws/l.txt"
    v = lambda flag, a, b: ("law_a = {\n" + ("\tflag = no\n" if flag else "")  # noqa: E731
                            + "".join(f"\t{k} = {a}\n" for k in "acde") + f"\tb = {b}\n}}\n")
    tr = build_tracker(tmp_path, [("1.0", {law: v(True, 1, 1)}), ("1.1", {law: v(False, 2, 1)}),
                                  ("1.2", {law: v(False, 2, 1) + "\n"}), ("1.3", {law: v(False, 2, 3)})])
    mod = tmp_path / "mod"
    fe = "in_game/common/laws/fe.txt"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', fe: "REPLACE:" + v(True, 2, 1)})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.2", "--new", "1.3",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    [f] = json.loads(plan.read_text(encoding="utf-8"))["files"]
    got = {d["path"][-1]["key"]: d for d in f["decisions"]}
    assert got["b"]["base_version"] == "1.1"          # the copy matches 1.1 best
    assert (got["flag"]["kind"], got["flag"]["action"]) == ("vanilla_removed", "open")
    assert "before --old 1.2" in got["flag"]["reason"]
    assert got["b"]["action"] == "take"
