"""A file that a tool generates gives one finding per file in the override, files
and GUI audits, never one per node, and only when vanilla changed its source."""
import io
from contextlib import redirect_stdout

from conftest import audit_args, build_tracker, make_ctx, _write_tree
from pdxaudit.files import run_file_audit
from pdxaudit.gui import run_gui_audit
from pdxaudit.overrides import run_override_audit

HEADER = "# AUTO-GENERATED by tools/compose_location_templates.py from vanilla. Do not hand-edit.\n"
REG = '[tool.compose_location_templates]\npath = "tools/compose_location_templates.py"\nstatus = "active"\n'
LOC = "in_game/map_data/location_templates.txt"
LAW = "in_game/common/laws/l.txt"
GUI = "in_game/gui/w.gui"


def _run(fn, tmp_path, mod_files, v1, v2):
    tr = build_tracker(tmp_path, [("1.0", v1), ("1.1", v2)])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', "pdx-maint.toml": REG, **mod_files})
    with redirect_stdout(io.StringIO()) as out:
        found = fn(mod, tr.repo, tr.hashes["1.0"], "1.0 Test", tr.hashes["1.1"], "1.1 Test",
                   audit_args(full=True), make_ctx(tr.repo, "1.1", fixed=True))
    return found, out.getvalue()


def test_a_generated_same_path_file_is_one_finding(tmp_path):
    v1 = {LOC: "a = { x = 1 }\nb = { x = 1 }\n"}
    v2 = {LOC: "a = { x = 2 }\nb = { x = 2 }\n"}
    found, out = _run(run_file_audit, tmp_path, {LOC: HEADER + "a = { x = 1 }\nb = { x = 1 }\n"}, v1, v2)
    assert [(f.kind, f.name) for f in found] == [("file_generated", LOC)]
    assert "pdx-maint run compose_location_templates" in found[0].detail
    assert "Files a tool generates" in out


def test_no_finding_when_vanilla_did_not_change_the_source(tmp_path):
    v = {LOC: "a = { x = 1 }\n"}
    found, _out = _run(run_file_audit, tmp_path, {LOC: HEADER + "a = { x = 5 }\n"}, v, v)
    assert found == []


def test_a_generated_replace_file_is_one_finding(tmp_path):
    v1 = {LAW: "law_a = {\n\tcost = 1\n}\nlaw_b = {\n\tcost = 1\n}\n"}
    v2 = {LAW: "law_a = {\n\tcost = 2\n}\nlaw_b = {\n\tcost = 2\n}\n"}
    mod = {"in_game/common/laws/fe_generated_l.txt":
           "# AUTO-GENERATED by generate_vanilla_overrides.py from l.txt\n"
           "REPLACE:law_a = {\n\tcost = 1\n}\nREPLACE:law_b = {\n\tcost = 1\n}\n"}
    found, _out = _run(run_override_audit, tmp_path, mod, v1, v2)
    assert [(f.kind, f.name) for f in found] == [("override_generated", "in_game/common/laws/fe_generated_l.txt")]


def test_a_generated_gui_file_is_one_finding(tmp_path):
    v1 = {GUI: "window = {\n\tsize = { 1 1 }\n}\n"}
    v2 = {GUI: "window = {\n\tsize = { 2 2 }\n}\n"}
    found, _out = _run(run_gui_audit, tmp_path, {GUI: HEADER + "window = {\n\tsize = { 1 1 }\n}\n"}, v1, v2)
    assert [(f.kind, f.name) for f in found] == [("gui_generated", GUI)]


def test_a_localization_header_is_read_after_the_language_key(tmp_path):
    from pdxaudit.registry import Registry
    root = tmp_path / "mod"
    _write_tree(root, {"pdx-maint.toml": REG, "x_l_english.yml": "l_english:\n" + HEADER + ' K:0 "v"\n'})
    assert Registry(root).generated_by("x_l_english.yml") == (True, "compose_location_templates")
