"""pdx-audit merge: the dry run writes a plan and nothing in the mod; --apply writes
only what the plan holds, and refuses a file that changed, failed the removed-line
check, holds an open decision or uses a stale entry."""
import json

from conftest import build_tracker, _write_tree
from pdxaudit.merge_cli import main

LAW = "in_game/common/laws/l.txt"
V1 = "law_a = {\n\tcost = 1\n\tx = 1\n}\n"
V2 = "law_a = {\n\tcost = 2\n\tx = 1\n\tnew = 1\n}\n"
MOD = "﻿REPLACE:law_a = {\n\tcost = 1\n\tx = 5\n}\n"
FE = "in_game/common/laws/fe.txt"


def _setup(tmp_path, monkeypatch, mod_text=MOD, extra=None):
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    tr = build_tracker(tmp_path, [("1.0", {LAW: V1}), ("1.1", {LAW: V2})])
    mod = tmp_path / "mod"
    files = {".metadata/metadata.json": '{"id": "t"}', FE: mod_text}
    files.update(extra or {})
    _write_tree(mod, files)
    common = ["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1"]
    return mod, common


def test_dry_run_writes_nothing_and_apply_writes_the_plan(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch)
    before = (mod / FE).read_bytes()
    plan = tmp_path / "plan.json"
    assert main(common + ["--dry-run", "--plan-out", str(plan)]) == 0
    out = capsys.readouterr().out
    assert (mod / FE).read_bytes() == before
    assert "+\tcost = 2" in out and "+\tnew = 1" in out and "Removed-line check: passed" in out
    assert main(common + ["--apply", str(plan)]) == 0
    after = (mod / FE).read_bytes()
    assert after.startswith(b"\xef\xbb\xbf")                       # the BOM stays
    assert after.decode("utf-8-sig") == "REPLACE:law_a = {\n\tcost = 2\n\tx = 5\n\tnew = 1\n}\n"


def test_apply_refuses_a_file_that_changed_after_the_dry_run(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch)
    plan = tmp_path / "plan.json"
    main(common + ["--dry-run", "--plan-out", str(plan)])
    (mod / FE).write_text(MOD.replace("x = 5", "x = 6"), encoding="utf-8")
    assert main(common + ["--apply", str(plan)]) == 1
    assert "changed after the dry run" in capsys.readouterr().err
    assert "cost = 1" in (mod / FE).read_text(encoding="utf-8-sig")


def test_apply_refuses_open_decisions_and_failed_checks(tmp_path, monkeypatch, capsys):
    mod, common = _setup(tmp_path, monkeypatch, MOD.replace("cost = 1", "cost = 3"))
    plan = tmp_path / "plan.json"
    main(common + ["--dry-run", "--plan-out", str(plan)])
    p = json.loads(plan.read_text())
    assert p["files"][0]["open"] == 1
    assert main(common + ["--apply", str(plan)]) == 1
    assert "open decisions" in capsys.readouterr().err
    p["files"][0]["open"] = 0
    p["files"][0]["removed_check"] = {"passed": False, "unexplained": [{"line": 2, "text": "x"}]}
    plan.write_text(json.dumps(p))
    assert main(common + ["--apply", str(plan)]) == 1
    assert "removed-line check failed" in capsys.readouterr().err


def test_generated_files_are_listed_to_regenerate(tmp_path, monkeypatch, capsys):
    reg = '[tool.gen]\npath = "tools/gen.py"\nstatus = "active"\n'
    mod, common = _setup(tmp_path, monkeypatch, "# AUTO-GENERATED by gen.py\n" + MOD.lstrip("﻿"),
                         {"pdx-maint.toml": reg})
    assert main(common + ["--dry-run", "--plan-out", str(tmp_path / "p.json")]) == 0
    out = capsys.readouterr().out
    assert "not merged; regenerate with `pdx-maint run gen`" in out
    assert "```diff" not in out


def test_a_repeated_key_merges_and_keeps_the_definitions_between(tmp_path, monkeypatch, capsys):
    """Vanilla 1.3.11 messagetypes.txt holds INDEPENDANCE two times, and 1.4 removes
    the second. The file audit reads both blocks as one copy, with the definitions
    between them blank. The merge must find that copy and keep those definitions."""
    path = "main_menu/gui/messagetypes.txt"
    v1 = "A={\nlog=yes\n}\n\nB={\nlog=yes\n}\n\nA={\nlog=no\n}\n\nC={\nlog=yes\n}\n"
    v2 = "A={\nlog=yes\n}\n\nB={\nlog=yes\n}\n\nC={\nlog=yes\n}\n"
    mod_text = ("﻿A = {\n\tlog = yes\n}\n\nB = {\n\tlog = yes\n\tmine = 1\n}\n\n"
                "A = {\n\tlog = no\n}\n\nC = {\n\tlog = yes\n}\n")
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "data"))
    tr = build_tracker(tmp_path, [("1.0", {path: v1}), ("1.1", {path: v2})])
    mod = tmp_path / "mod"
    _write_tree(mod, {".metadata/metadata.json": '{"id": "t"}', path: mod_text})
    plan = tmp_path / "plan.json"
    assert main(["--mod-root", str(mod), "--vanilla-repo", tr.repo, "--old", "1.0", "--new", "1.1",
                 "--dry-run", "--plan-out", str(plan)]) == 0
    p = json.loads(plan.read_text(encoding="utf-8"))
    assert not p["skipped"]
    [f] = p["files"]
    assert f["removed_check"]["passed"] and not f["open"]
    assert f["merged"] == "A = {\n\tlog = yes\n}\n\nB = {\n\tlog = yes\n\tmine = 1\n}\n\n\nC = {\n\tlog = yes\n}\n"
