"""The mod's pdx-maint registry, read only.

`pdx-maint.toml` at the mod root lists the mod's systems (`[system.<id>]`, with
`files` globs) and tools (`[tool.<id>]`, with `path`, `status`, `outputs`, `header`
and `run`). The intent store names a system for each rule and entry, and a rule can
name the tool that maintains it. A file that a tool generates is never merged: the
report names the tool, and `pdx-maint run <id>` regenerates the file.

pdx-audit never imports mod code and never runs a mod tool here. It reads the
registry file only."""
import json
import re
from functools import lru_cache
from pathlib import Path

try:
    import tomllib
except ImportError:                      # Python 3.10
    tomllib = None

from . import session

REGISTRY = "pdx-maint.toml"
# The markers the mod's lint reads on the first line (tools/lint/_blocks.py is_generated).
GENERATED_MARKERS = ("AUTO-GENERATED", "Generated by tools/", "GENERATED by")


@lru_cache(maxsize=None)
def glob_regex(pattern):
    """A regex for a registry glob: `**` is any number of folders, `*` is any text in
    one folder, `?` is one character."""
    out, i = [], 0
    while i < len(pattern):
        c = pattern[i]
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
            continue
        if pattern.startswith("**", i):
            out.append(".*")
            i += 2
            continue
        out.append("[^/]*" if c == "*" else "[^/]" if c == "?" else re.escape(c))
        i += 1
    return re.compile("".join(out) + r"\Z")


class Registry:
    """The systems and tools of one mod. An empty registry when the mod has none."""

    def __init__(self, mod_root, data=None):
        self.mod_root = Path(mod_root)
        self.data = data if data is not None else self._read()
        self.systems = {k: v for k, v in self.data.get("system", {}).items() if isinstance(v, dict)}
        self.tools = {k: v for k, v in self.data.get("tool", {}).items() if isinstance(v, dict)}
        self._systems_cache, self._generated_cache = {}, {}

    def _read(self):
        path = self.mod_root / REGISTRY
        if tomllib is None or not path.is_file():
            return {}
        try:
            return tomllib.loads(path.read_text(encoding="utf-8-sig"))
        except (OSError, ValueError):
            return {}

    @property
    def present(self):
        return bool(self.systems or self.tools)

    def systems_of(self, rel):
        """The ids of the systems whose `files` globs match the mod path `rel`."""
        hit = self._systems_cache.get(rel)
        if hit is None:
            hit = self._systems_cache[rel] = [
                sid for sid, s in self.systems.items()
                if any(glob_regex(g).match(rel) for g in s.get("files", []) if isinstance(g, str))]
        return list(hit)

    def header_names(self, tid):
        tool = self.tools.get(tid, {})
        if "header" in tool:
            return [h for h in tool["header"] if isinstance(h, str)]
        path = tool.get("path", "")
        return [Path(path).name] if path else []

    def generated_by(self, rel, text=None):
        """(True, tool id or None) when a tool generates the mod file `rel`, else
        (False, None). Kept for each file."""
        if text is None and rel in self._generated_cache:
            return self._generated_cache[rel]
        out = self._generated_by(rel, text)
        if text is None:
            self._generated_cache[rel] = out
        return out

    def _generated_by(self, rel, text=None):
        """(True, tool id or None) when a tool generates the mod file `rel`, else
        (False, None). A tool generates a file that it lists in `outputs`, or whose
        first "generated by" header line names it."""
        for tid, tool in self.tools.items():
            if tool.get("status") == "retired":
                continue
            for g in tool.get("outputs", []):
                if not isinstance(g, str):
                    continue
                if g.startswith("manifest:") and rel in self.manifest(g[len("manifest:"):]):
                    return True, tid
                if not g.startswith("manifest:") and glob_regex(g).match(rel):
                    return True, tid
        line = header_line(self.mod_root / rel) if text is None else _first_line(text)
        if not any(m in line for m in GENERATED_MARKERS):
            return False, None
        for tid, tool in self.tools.items():
            if tool.get("status") == "retired":
                continue
            for name in self.header_names(tid):
                if re.search(r"(?<![\w.-])" + re.escape(name) + r"(?![\w-])", line):
                    return True, tid
        return True, None

    def manifest(self, rel):
        """The mod paths a tool's manifest lists: `manifest:<file>` in `outputs` names
        a file the tool writes, a JSON list of paths or one path on each line (the
        pdx-maint form). An absent or unreadable manifest lists nothing: the tool
        has not run in this checkout, so no file is its output yet."""
        key = ("manifest", rel)
        if key not in self._generated_cache:
            try:
                text = (self.mod_root / rel).read_text(encoding="utf-8-sig")
            except OSError:
                text = ""
            try:
                items = json.loads(text) if text.strip() else []
            except ValueError:
                items = [ln.strip() for ln in text.splitlines() if ln.strip()]
            self._generated_cache[key] = {str(x) for x in items} if isinstance(items, list) else set()
        return self._generated_cache[key]

    def regenerate_hint(self, tid):
        if tid:
            return f"regenerate with `pdx-maint run {tid}`"
        return "regenerate with the tool that wrote its header"


def _first_line(text):
    lines = text.lstrip("\ufeff").split("\n", 2)
    if re.match(r"\s*l_\w+:\s*$", lines[0]) and len(lines) > 1:
        return lines[1]
    return lines[0]


def header_line(path):
    """The line that carries a generator header: the first line, or in a localization
    file the line after its language key. Read only, and only the start of the file."""
    try:
        with open(path, encoding="utf-8-sig", errors="replace") as f:
            first = f.readline()
            if re.match(r"\s*l_\w+:\s*$", first):
                first = f.readline()
            return first
    except OSError:
        return ""


class Generated:
    """The mod files a tool generates that an audit met, with the newest vanilla change
    in the window. An audit reports each as one finding, never node by node: the tool
    reads vanilla again."""

    def __init__(self, mod_root, ctx=None):
        self.reg = registry(mod_root)
        self.files = {}                          # rel: (tool, index of the version, tag)
        self.ctx = ctx

    def check(self, rel):
        return self.reg.generated_by(rel)

    def add(self, rel, tool, texts, tags):
        """Note a generated file when vanilla's text in `texts` (oldest first) changed in
        the window; `tags` names each version."""
        changed = [k for k in range(1, len(texts)) if texts[k] != texts[k - 1]]
        if not changed:
            return
        k = changed[-1]
        old = self.files.get(rel)
        if old is None or old[1] < k:
            self.files[rel] = (tool, k, tags[k])
        if self.ctx is not None and hasattr(self.ctx, "generated"):
            self.ctx.generated[rel] = tool

    def findings(self, kind):
        from .report import Finding
        out = []
        for rel, (tool, _k, tag) in sorted(self.files.items()):
            out.append(Finding(kind, rel, f"{rel}:1", f"generated by {tool or 'a tool'}; "
                               + self.reg.regenerate_hint(tool) + " after the patch", None,
                               {"target": f"generated:{rel}", "tool": tool, "since": tag}, tag))
        return out

    def print(self):
        if not self.files:
            return
        print("## Files a tool generates")
        print()
        for rel, (tool, _k, tag) in sorted(self.files.items()):
            print(f"- `{rel}`: vanilla changed its source in {tag}; {self.reg.regenerate_hint(tool)}")
        print()


def registry(mod_root):
    return session.memo(("registry", str(mod_root)), lambda: Registry(mod_root))
