"""The mod's pdx-maint registry, read only.

`pdx-maint.toml` at the mod root lists the mod's systems (`[system.<id>]`, with
`files` globs) and tools (`[tool.<id>]`, with `path`, `status`, `outputs`, `header`
and `run`). The intent store names a system for each rule and entry, and a rule can
name the tool that maintains it. A file that a tool generates is never merged: the
report names the tool, and `pdx-maint run <id>` regenerates the file.

pdx-audit never imports mod code and never runs a mod tool here. It reads the
registry file only."""
import re
from functools import lru_cache
from pathlib import Path

try:
    import tomllib
except ImportError:                      # Python 3.10
    tomllib = None

from . import session

REGISTRY = "pdx-maint.toml"
HEADER_LINES = 12
# The same test pdx-maint uses: only the first "generated by" line names a generator.
GENERATED_RE = re.compile(r"(?i)(?:auto-)?generated by\s+(?:tools/)?([\w./-]*\w)")


@lru_cache(maxsize=None)
def glob_regex(pattern):
    """A regex for a registry glob: `**` is any number of folders, `*` is any text in
    one folder, `?` is one character."""
    out, i = [], 0
    while i < len(pattern):
        c = pattern[i]
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
            continue
        if pattern.startswith("**", i):
            out.append(".*")
            i += 2
            continue
        out.append("[^/]*" if c == "*" else "[^/]" if c == "?" else re.escape(c))
        i += 1
    return re.compile("".join(out) + r"\Z")


class Registry:
    """The systems and tools of one mod. An empty registry when the mod has none."""

    def __init__(self, mod_root, data=None):
        self.mod_root = Path(mod_root)
        self.data = data if data is not None else self._read()
        self.systems = {k: v for k, v in self.data.get("system", {}).items() if isinstance(v, dict)}
        self.tools = {k: v for k, v in self.data.get("tool", {}).items() if isinstance(v, dict)}
        self._systems_cache, self._generated_cache = {}, {}

    def _read(self):
        path = self.mod_root / REGISTRY
        if tomllib is None or not path.is_file():
            return {}
        try:
            return tomllib.loads(path.read_text(encoding="utf-8-sig"))
        except (OSError, ValueError):
            return {}

    @property
    def present(self):
        return bool(self.systems or self.tools)

    def systems_of(self, rel):
        """The ids of the systems whose `files` globs match the mod path `rel`."""
        hit = self._systems_cache.get(rel)
        if hit is None:
            hit = self._systems_cache[rel] = [
                sid for sid, s in self.systems.items()
                if any(glob_regex(g).match(rel) for g in s.get("files", []) if isinstance(g, str))]
        return list(hit)

    def header_names(self, tid):
        tool = self.tools.get(tid, {})
        if "header" in tool:
            return [h for h in tool["header"] if isinstance(h, str)]
        path = tool.get("path", "")
        return [Path(path).name] if path else []

    def generated_by(self, rel, text=None):
        """(True, tool id or None) when a tool generates the mod file `rel`, else
        (False, None). Kept for each file."""
        if text is None and rel in self._generated_cache:
            return self._generated_cache[rel]
        out = self._generated_by(rel, text)
        if text is None:
            self._generated_cache[rel] = out
        return out

    def _generated_by(self, rel, text=None):
        """(True, tool id or None) when a tool generates the mod file `rel`, else
        (False, None). A tool generates a file that it lists in `outputs`, or whose
        first "generated by" header line names it."""
        for tid, tool in self.tools.items():
            if tool.get("status") == "retired":
                continue
            if any(glob_regex(g).match(rel) for g in tool.get("outputs", []) if isinstance(g, str)):
                return True, tid
        if text is None:
            try:
                text = session.read_text(self.mod_root / rel)
            except (OSError, UnicodeDecodeError):
                return False, None
        for line in text.split("\n", HEADER_LINES)[:HEADER_LINES]:
            m = GENERATED_RE.search(line)
            if not m:
                continue
            for tid, tool in self.tools.items():
                for name in self.header_names(tid):
                    if re.search(r"(?<![\w.-])" + re.escape(name) + r"(?![\w-])", line):
                        return True, tid
            return True, None
        return False, None

    def regenerate_hint(self, tid):
        if tid:
            return f"regenerate with `pdx-maint run {tid}`"
        return "regenerate with the tool that wrote its header"


def registry(mod_root):
    return session.memo(("registry", str(mod_root)), lambda: Registry(mod_root))
